### ISSUE TITLE
PartNet code typo

### ISSUE THREAD

**Issue by Hippogriff** [lightaime/deep_gcns_torch#25]
Hi! There is a typo:
https://github.com/lightaime/deep_gcns_torch/blob/master/examples/part_sem_seg/main.py#L164

It should be the val_dataset not test_dataset for validation loader.
Thank you.

**Comment by lightaime** [comment]
Thanks, we knew this. The old version of code on PartNet is not clean and has some flaws. We are going to update the new version of code in several hours. And the new version of preprint in this month. I apologize for the inconvenience since the journal extension of our paper is still working in procees.

**Comment by Hippogriff** [comment]
Oh, no problem. No hurries. Thank you.

**Comment by guochengqian** [comment]
Hi. Sorry for the typo. We are too busy with the submission that we forget to update the code in Github since it is still an ongoing project. The original version has some flaws. We found that months ago and only update our code locally. 
Now we push the latest code for PartNet.  We will release our pretrained models later.
