### ISSUE TITLE
In the class GENConv, should the output dimension of edge_encoder be in_dim instead of emb_dim?

### ISSUE THREAD

**Issue by youngleec** [lightaime/deep_gcns_torch#59]
Hi, your work is great and interests me a lot.

In the class **GENConv**, should the output dimension of **edge_encoder** be **in_dim** instead of **emb_dim**, especially when the **in_dim** doesn't equal to the **emb_dim**? Thanks.

https://github.com/lightaime/deep_gcns_torch/blob/03d553d1a75e923586e0e67b9fdf69dfd31e481b/gcn_lib/sparse/torch_vertex.py#L57

**Comment by lightaime** [comment]
Hi @youngleec. You are right. It should be in_dim instead of emb_dim for the case when in_dim != emb_dim. I noticed this and fixed it when I created a pull request for PyG (https://github.com/rusty1s/pytorch_geometric/pull/1403/commits/a173c0794493e2842a2379efe09fea9b6d649cc6). But I forgot to change it here. Thanks for your reminder.
