### ISSUE TITLE
About OGB submission

### ISSUE THREAD

**Issue by weihua916** [lightaime/deep_gcns_torch#88]
Thanks for your ogbn-proteins submissions. Could you clearly specify the exact command to reproduce your reported result? We will update the leaderboard once this is confirmed.

I was confused since you provide multiple training and inference schemes. I would like you to make it clear which one you use to obtain the reported result.

**Comment by lightaime** [comment]
Hi @weihua916. Thanks for your suggestion. There are two submitted models. I added more descriptions to the README. Could you also help with changing the required hardware as NVIDIA RTX 6000 (48G) since inference on larger subgraphs needs more memory? Please let me know if you have any other questions.

**Comment by weihua916** [comment]
Great, things are clearer now. Maybe you can make it clear that ROC-AUC is "Test ROC-AUC". Otherwise, looks great. Will update the leaderboard. Thanks!

The hardware is also fixed.

**Comment by lightaime** [comment]
Thanks! Changed it accordingly. Will finetune more and upload the pre-trained models soon.

**Comment by weihua916** [comment]
Great, the leaderboards have been updated.
