### ISSUE TITLE
AttributeError: 'tuple' object has no attribute 'num_nodes'

### ISSUE THREAD

**Issue by zsz00** [lightaime/deep_gcns_torch#9]
multi_gpus  have error .

python -u examples/ppi/main.py --phase train --data_dir data --block res --n_filters 256 --n_blocks 28    is ok .  
But, 
python -u examples/ppi/main.py --phase train --data_dir data --block res --n_filters 256 --n_blocks 28 --multi_gpus --batch_size 4
is error: 
AttributeError: 'tuple' object has no attribute 'num_nodes'

**Comment by guochengqian** [comment]
Hello. @zsz00 This problem is from the data parallel function of Pytorch. However, Pytorch geometric (PyG) is not compatible with the data parallel function of Pytorch. 

We did not use multi_gpu. We only test our code by using only one batch_size and on GPU, which is suggested in the previous research work, since PPI is a really small dataset.  If you really need multiple GPUs, you can easily solve the problem by replacing the data-parallel function with the one provided by PyG.
